package GUI;

import PKG.Common.IServidor;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FramePrincipal extends javax.swing.JFrame {
    private IServidor server;
    public FramePrincipal() {
        initComponents();
        textoMontoConsulta.setFocusable(false);
        this.setLocationRelativeTo(null);
        
        this.setSize(400,325);
        panelPrincipal.setSize(400, 325);
        panelDeposito.setSize(400, 210);
        panelExtraccion.setSize(400, 210);
        panelConsulta.setSize(400,210);
        panelPrincipal.setVisible(true);
        panelDeposito.setVisible(false);
        panelExtraccion.setVisible(false);
        panelConsulta.setVisible(false);
    }
    
    public void setServidor(IServidor s){
        server = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botonExtraer = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelDeposito = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonRegreso1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        textoID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoMonto = new javax.swing.JTextField();
        botonDepositar = new javax.swing.JButton();
        panelExtraccion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonRegreso2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoMontoExtract = new javax.swing.JTextField();
        textoIDExtract = new javax.swing.JTextField();
        panelConsulta = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        textoMontoConsulta = new javax.swing.JTextField();
        textoIDConsulta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de cuentas");
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        panelPrincipal.setBackground(new java.awt.Color(0, 102, 153));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(400, 300));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(231, 180, 13));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú Principal");
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 190, 30));

        jButton1.setText("Depositar saldo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 190, 30));

        botonExtraer.setText("Extraer monto");
        botonExtraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExtraerActionPerformed(evt);
            }
        });
        panelPrincipal.add(botonExtraer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 190, 30));

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, 30));

        jButton4.setText("Consultar saldo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 190, 30));

        panelDeposito.setBackground(new java.awt.Color(0, 102, 153));
        panelDeposito.setMaximumSize(new java.awt.Dimension(400, 300));
        panelDeposito.setMinimumSize(new java.awt.Dimension(400, 300));
        panelDeposito.setPreferredSize(new java.awt.Dimension(400, 210));
        panelDeposito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(231, 180, 13));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Depositar");
        panelDeposito.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, 30));

        botonRegreso1.setText("Regresar");
        botonRegreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegreso1ActionPerformed(evt);
            }
        });
        panelDeposito.add(botonRegreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingrese ID de la cuenta:");
        panelDeposito.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 20));
        panelDeposito.add(textoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, 22));
        textoID.getAccessibleContext().setAccessibleName("");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cuanto desea depositar:");
        panelDeposito.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        textoMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoMontoActionPerformed(evt);
            }
        });
        panelDeposito.add(textoMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, 22));
        textoMonto.getAccessibleContext().setAccessibleName("");

        botonDepositar.setText("Depositar");
        botonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDepositarActionPerformed(evt);
            }
        });
        panelDeposito.add(botonDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        panelExtraccion.setBackground(new java.awt.Color(0, 102, 153));
        panelExtraccion.setPreferredSize(new java.awt.Dimension(400, 210));
        panelExtraccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(231, 180, 13));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Extracciones");
        panelExtraccion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, 30));

        botonRegreso2.setText("Regresar");
        botonRegreso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegreso2ActionPerformed(evt);
            }
        });
        panelExtraccion.add(botonRegreso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jButton2.setText("Extraer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelExtraccion.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese ID de la cuenta:");
        panelExtraccion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese monto a extraer:");
        panelExtraccion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));
        panelExtraccion.add(textoMontoExtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, 22));
        panelExtraccion.add(textoIDExtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, 22));

        panelConsulta.setBackground(new java.awt.Color(0, 102, 153));
        panelConsulta.setPreferredSize(new java.awt.Dimension(400, 210));
        panelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingrese ID de la cuenta:");
        panelConsulta.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Monto de la cuenta:");
        panelConsulta.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 20));

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelConsulta.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jButton6.setText("Consultar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelConsulta.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));
        panelConsulta.add(textoMontoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, 22));
        panelConsulta.add(textoIDConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, 22));

        jLabel11.setBackground(new java.awt.Color(0, 102, 204));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Consulta");
        panelConsulta.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelExtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelExtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelPrincipal.setVisible(false);
        panelDeposito.setVisible(true);
        panelExtraccion.setVisible(false);
        panelConsulta.setVisible(false);
        this.setSize(400, 210);
        this.validate();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonExtraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExtraerActionPerformed
        panelPrincipal.setVisible(false);
        panelDeposito.setVisible(false);
        panelExtraccion.setVisible(true);
        panelConsulta.setVisible(false);
        this.setSize(400, 210);
        this.validate(); 
    }//GEN-LAST:event_botonExtraerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonRegreso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegreso2ActionPerformed
        panelPrincipal.setVisible(true);
        panelDeposito.setVisible(false);
        panelExtraccion.setVisible(false);
        panelConsulta.setVisible(false);
        this.setSize(400, 325);
        this.validate();
    }//GEN-LAST:event_botonRegreso2ActionPerformed

    private void botonRegreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegreso1ActionPerformed
        panelPrincipal.setVisible(true);
        panelDeposito.setVisible(false);
        panelExtraccion.setVisible(false);
        panelConsulta.setVisible(false);
        this.setSize(400, 325);
        this.validate();
    }//GEN-LAST:event_botonRegreso1ActionPerformed

    private void textoMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMontoActionPerformed

    private void botonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDepositarActionPerformed
        boolean retorno;
        if(!textoID.getText().matches("^[0-9]+$")){
            JOptionPane.showMessageDialog(null, "El ID solo puede ser un número!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(!textoMonto.getText().matches("^(([0-9]+\056[0-9][0-9])|([0-9]+))$")){
            JOptionPane.showMessageDialog(null, "El monto solo puede ser un número entero o real con 2 digitos detras del punto!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int id = Integer.parseInt(textoID.getText());
            double monto = Double.parseDouble(textoMonto.getText());
            try {
                retorno = server.depositar(id, monto);
                if (retorno){
                    JOptionPane.showMessageDialog(null, "Ha depositado $"+monto+" en la cuenta "+id+" correctamente.", "Deposito Exitoso!", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "El ID de la cuenta no existe!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                textoID.setText("");
                textoMonto.setText("");
            } catch (RemoteException ex) {
                Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonDepositarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!textoIDExtract.getText().matches("^[0-9]+$")){
            JOptionPane.showMessageDialog(null, "El ID solo puede ser un número!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(!textoMontoExtract.getText().matches("^(([0-9]+\056[0-9][0-9])|([0-9]+))$")){
            JOptionPane.showMessageDialog(null, "El monto solo puede ser un número entero o real con 2 digitos detras del punto!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int id = Integer.parseInt(textoIDExtract.getText());
            double monto = Double.parseDouble(textoMontoExtract.getText());
            int retorno;
            try {
                retorno = server.extraer(id, monto);
                if(retorno == 1){
                    JOptionPane.showMessageDialog(null, "Ha extraido correctamente", "Extracción Exitosa!", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(retorno == 0){
                    JOptionPane.showMessageDialog(null, "El monto solicitado es mayor al de la cuenta", "Error!", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "El ID solicitado no existe!", "Error!", JOptionPane.ERROR_MESSAGE);
                }
                textoIDExtract.setText("");
                textoMontoExtract.setText("");
            } catch (RemoteException ex) {
                Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        panelPrincipal.setVisible(false);
        panelDeposito.setVisible(false);
        panelExtraccion.setVisible(false);
        panelConsulta.setVisible(true);
        this.setSize(400,210);
        this.validate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        textoMontoConsulta.setText("");
        textoIDConsulta.setText("");
        
        panelPrincipal.setVisible(true);
        panelDeposito.setVisible(false);
        panelExtraccion.setVisible(false);
        panelConsulta.setVisible(false);
        this.setSize(400,325);
        this.validate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(!textoIDConsulta.getText().matches("^[0-9]+$")){
            JOptionPane.showMessageDialog(null, "El ID solo puede ser un número!", "Error", JOptionPane.ERROR_MESSAGE);
            textoMontoConsulta.setText("");
        }
        else{
            int id = Integer.parseInt(textoIDConsulta.getText());
            try {
                double monto = server.consultarSaldo(id);
                if(monto==-1){
                    JOptionPane.showMessageDialog(null, "El ID no existe!", "Error", JOptionPane.ERROR_MESSAGE);
                    textoMontoConsulta.setText("");
                }
                else{
                    String montoText = Double.toString(monto);
                    textoMontoConsulta.setText("$"+montoText);
                }
            } catch (RemoteException ex) {
                Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDepositar;
    private javax.swing.JButton botonExtraer;
    private javax.swing.JButton botonRegreso1;
    private javax.swing.JButton botonRegreso2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelConsulta;
    private javax.swing.JPanel panelDeposito;
    private javax.swing.JPanel panelExtraccion;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField textoID;
    private javax.swing.JTextField textoIDConsulta;
    private javax.swing.JTextField textoIDExtract;
    private javax.swing.JTextField textoMonto;
    private javax.swing.JTextField textoMontoConsulta;
    private javax.swing.JTextField textoMontoExtract;
    // End of variables declaration//GEN-END:variables
}
